# Generated by Django 5.2.9 on 2025-12-10 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales_order", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="salesorderline",
            name="price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
    ]
